POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json


{
    "id": "d811e46d-70b3-4d90-b090-4535c7cf8fb1",
    "date": "2015-01-02",
    "type": "HealthCheck",
    "specialist": "MD Simojoki",
    "diagnosisCodes": ["S62.5"],
    "description":
    "Patient accidentally dropped from 200 feet. Surprisingly little amount of injuries.",
    "healthCheckRating": 5
}
